# 1) Specify the main command (either 'predict' or 'evaluate')
command :

# 2) Specify the command-related parameters
# 2)a FOR PREDICTION ONLY
# NB: subcommand in ['dataset']
prediction :
    subcommand : dataset
    model_path : [/home/user]/asm-map/data/models/Unet_2021-05-16/data/model.h5
    tifs_folder_path : [/home/user]/asm-map/data/test-images/Sub-Tropical_West_Africa/images
    output_folder_path :
    binary_threshold : 0.5

# 2)b FOR EVALUATION ONLY
# NB: subcommand in ['all', 'threshold', 'size', 'biomes', 'roc', 'matrix']
evaluation :
    subcommand :
    gt_folder_path : [/home/user]/asm-map/data/test-images/Sub-Tropical_West_Africa/ground_truth
    pred_folder_path :
    eval_folder_path :
    gt_asm_shapefile : [/home/user]/asm-map/data/test-images/Sub-Tropical_West_Africa/gt_asm_shapes.shp
    aoi_shapefile : [/home/user]/asm-map/data/shapefiles/subtropical_west_africa_region.shp
# Additional parameters for threshold metric only (i.e. unused if subcommand is not 'threshold')
    no_mcc :
    no_fscore :
    output_filename :
